export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREASE_QUANT = "INCREASE_QUANT";
export const DECREASE_QUANT = "DECREASE_QUANT"
export const GET_TOTALS = "GET_TOTALS";